---

- name: "Provision a Docker Swarm cluster"
  hosts: docker_engine
  vars:
    docker_yum_repo: https://download.docker.com/linux/centos/7/aarch64/stable/
  roles:
    - { role: ansible-dockerswarm }
